apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Values.namespaces.observability }}
  labels:
    app: {{ .Values.promtail.name }}
    {{- if .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
data:
  promtail.yaml: |
    server:
      http_listen_port: {{ .Values.promtail.service.port }}
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://{{ .Values.loki.name }}.{{ .Values.namespaces.observability }}.svc.cluster.local:{{ .Values.loki.service.port }}/loki/api/v1/push
        tenant_id: "default"
        batchwait: 1s
        batchsize: 102400
        follow_redirects: true
        tls_config:
          insecure_skip_verify: true

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
          - cri: {}
          - json:
              expressions:
                level: level
                message: message
                timestamp: time
                caller: caller
          - timestamp:
              source: timestamp
              format: RFC3339Nano
          - labels:
              level:
          - output:
              source: message
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __meta_kubernetes_pod_label_k8s_app
              - __meta_kubernetes_pod_label_component
              - __meta_kubernetes_pod_controller_name
              - __meta_kubernetes_pod_name
            regex: '(;*([^;]+))?;(;*([^;]+))?;(;*([^;]+))?;(;*([^;]+))?;(;*([^;]+))?;(.*)'
            target_label: app
            replacement: '${2}${4}${6}${8}${10}${11}'
            action: replace
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node_name
            action: replace
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - app
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            regex: (.*)
            target_label: namespace
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: replace
            regex: (.*)
            target_label: container
            replacement: $1
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            regex: (.*)
            target_label: pod
            replacement: $1
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - namespace
              - app
            target_label: job 