apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.name }}
  namespace: {{ .Values.namespaces.observability }}
  labels:
    app: {{ .Values.loki.name }}
    {{- if .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.loki.service.port }}"
spec:
  type: {{ .Values.loki.service.type }}
  ports:
  - port: {{ .Values.loki.service.port }}
    targetPort: http-loki
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.loki.name }} 