# Namespace configurations
namespaces:
  observability: observability
  app: app-order

# Skip namespace template if it already exists 
# (useful when deploying with helm upgrade)
skipNamespaceTemplate: false

# Grafana configuration
grafana:
  name: grafana
  image:
    repository: grafana/grafana
    tag: 9.3.2
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 30300
  adminUser: admin
  adminPassword: admin123
  plugins: "grafana-polystat-panel, grafana-piechart-panel"
  allowUnsignedPlugins: "grafana-polystat-panel"
  resources:
    requests:
      memory: "750Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Prometheus configuration
prometheus:
  name: prometheus
  image:
    repository: prom/prometheus
    tag: v2.37.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
  resources:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  retention: 24h
  extraArgs:
    - "--storage.tsdb.retention.size=2GB" 
    - "--web.enable-lifecycle"
    - "--storage.tsdb.no-lockfile"

# Loki configuration
loki:
  name: loki
  image:
    repository: grafana/loki
    tag: 2.8.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3100
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "300m"

# Promtail configuration
promtail:
  name: promtail
  image:
    repository: grafana/promtail
    tag: 2.8.2
    pullPolicy: IfNotPresent
  service:
    port: 3101
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "150m"

# Target namespaces to monitor
targetNamespaces:
  - app-order
  - observability 

# Node Exporter configuration for system metrics
nodeExporter:
  name: node-exporter
  enabled: true
  image:
    repository: prom/node-exporter
    tag: v1.5.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9100
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

# Kube State Metrics configuration
kubeStateMetrics:
  name: kube-state-metrics
  enabled: true
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: v2.8.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

# cAdvisor configuration for container metrics
cadvisor:
  name: cadvisor
  enabled: true
  image:
    repository: gcr.io/cadvisor/cadvisor
    tag: v0.47.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "300m"