# Namespace configurations
namespaces:
  app: app-order

# DynamoDB configuration
dynamodb:
  name: dynamodb-local
  image:
    repository: amazon/dynamodb-local
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Grafana configuration
grafana:
  name: grafana
  image:
    repository: grafana/grafana
    tag: 9.3.2
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 30300
  adminUser: admin
  adminPassword: admin123
  plugins: "grafana-polystat-panel, grafana-piechart-panel"
  allowUnsignedPlugins: "grafana-polystat-panel"
  resources:
    requests:
      memory: "750Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Prometheus configuration
prometheus:
  name: prometheus
  image:
    repository: prom/prometheus
    tag: v2.37.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  retention: 24h

# Order API configuration
orderApi:
  name: order-api
  image:
    repository: order-api
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 8000
    nodePort: 30001
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  env:
    AWS_ACCESS_KEY_ID: "local"
    AWS_SECRET_ACCESS_KEY: "local"
    AWS_DEFAULT_REGION: "us-west-2"
    DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
    DYNAMODB_TABLE: "orders"
    ORDER_PROCESSOR_URL: "http://order-processor:8000"

# Order Processor configuration
orderProcessor:
  name: order-processor
  image:
    repository: order-processor
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  env:
    AWS_ACCESS_KEY_ID: "local"
    AWS_SECRET_ACCESS_KEY: "local"
    AWS_DEFAULT_REGION: "us-west-2"
    DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
    DYNAMODB_TABLE: "inventory"
