{{- if not .Values.skipNamespaceTemplate }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.observability }}
  labels:
    name: {{ .Values.namespaces.observability }}
{{- end }} 