apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderApi.name }}
  namespace: {{ .Values.namespaces.app }}
  labels:
    app: {{ .Values.orderApi.name }}
    {{- if .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: {{ .Values.orderApi.service.type }}
  ports:
  - port: {{ .Values.orderApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if (eq .Values.orderApi.service.type "NodePort") }}
    nodePort: {{ .Values.orderApi.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Values.orderApi.name }} 